# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-03 17:03
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=50)),
                ('slug', models.SlugField(default=b'')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child', to='product.Category')),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='DietList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diet_type', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_code', models.PositiveIntegerField(default=1)),
                ('product_name', models.CharField(default=b'', max_length=200)),
                ('price', models.FloatField(default=1.0)),
                ('sale_price', models.FloatField(blank=True, default=b'', null=True)),
                ('active', models.IntegerField(default=b'1')),
                ('allergen', models.CharField(blank=True, default=b'None', max_length=900)),
                ('weight', models.FloatField(default=1.0)),
                ('product_details', models.TextField(blank=True)),
                ('ingredients', models.CharField(blank=True, default=b'', max_length=900)),
                ('unique_product', models.BooleanField(default=False)),
                ('diet_list', models.ManyToManyField(default=b'', related_name='product', to='product.DietList')),
                ('group_categories', models.ManyToManyField(default=b'', related_name='product', to='product.Category')),
                ('unique_product_for_customer', models.ForeignKey(default=b'', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['item_code'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='category',
            unique_together=set([('parent', 'slug')]),
        ),
    ]
