# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-03 17:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20180203_1706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sale_price',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
