# Generated by Django 2.1.4 on 2018-12-23 14:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=50)),
                ('slug', models.SlugField(default='')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child', to='web.Category')),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='CustomerProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(blank=True, default='', max_length=200)),
                ('email_address', models.EmailField(blank=True, default='', max_length=500)),
                ('phone', models.BigIntegerField(default=0)),
                ('addressline1', models.CharField(blank=True, default='', max_length=200)),
                ('addressline2', models.CharField(blank=True, default='', max_length=200)),
                ('postcode', models.CharField(blank=True, default='', max_length=10)),
                ('account_created_date', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DietList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diet_type', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_code', models.PositiveIntegerField(default=1)),
                ('product_name', models.CharField(default='', max_length=200)),
                ('price', models.FloatField(default=1.0)),
                ('sale_price', models.FloatField(blank=True, default=None, null=True)),
                ('active', models.IntegerField(default='1')),
                ('allergen', models.CharField(blank=True, default='None', max_length=900)),
                ('weight', models.FloatField(default=1.0)),
                ('product_details', models.TextField(blank=True)),
                ('ingredients', models.CharField(blank=True, default='', max_length=900)),
                ('unique_product', models.BooleanField(default=False)),
                ('diet_list', models.ManyToManyField(default='', related_name='product', to='web.DietList')),
                ('group_categories', models.ManyToManyField(default='', related_name='product', to='web.Category')),
                ('unique_product_for_customer', models.ForeignKey(default='', on_delete=None, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['item_code'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='category',
            unique_together={('parent', 'slug')},
        ),
    ]
