# Generated by Django 2.1.4 on 2018-12-23 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerprofile',
            name='products',
            field=models.ManyToManyField(default='', to='web.Product'),
        ),
        migrations.AlterField(
            model_name='product',
            name='group_categories',
            field=models.ManyToManyField(default='', to='web.Category'),
        ),
    ]
