# Generated by Django 2.1.4 on 2019-01-15 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_auto_20190115_1307'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='product_id',
            new_name='order_detail',
        ),
        migrations.AddField(
            model_name='order',
            name='tracking_number',
            field=models.CharField(default='test', max_length=40),
            preserve_default=False,
        ),
    ]
