# Generated by Django 2.1.4 on 2019-01-15 13:28

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_auto_20190115_1312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='tracking_number',
            field=models.CharField(blank=True, default=uuid.uuid4, max_length=30, unique=True),
        ),
    ]
