# Generated by Django 2.1.4 on 2019-01-15 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_auto_20190115_1349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='tracking_number',
            field=models.CharField(blank=True, default='11b18fee', max_length=8, unique=True),
        ),
    ]
